# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 763)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #22222e")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 480, 270))
        font = QtGui.QFont()
        font.setFamily("STHupo")
        font.setPointSize(22)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: #FFFACD")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 421, 41))
        font = QtGui.QFont()
        font.setFamily("STHupo")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: black\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 80, 181, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Downloads/рисунок8.FGjyp.png"))
        self.label_2.setObjectName("label_2")
        self.input_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.input_currency.setGeometry(QtCore.QRect(50, 320, 380, 60))
        font = QtGui.QFont()
        font.setFamily("STHupo")
        font.setPointSize(14)
        self.input_currency.setFont(font)
        self.input_currency.setStyleSheet("background-color: #FFFACD;\n"
"border: 2px solid #6B8E23;\n"
"border-radius: 30;\n"
"color: black\n"
"")
        self.input_currency.setText("")
        self.input_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.input_currency.setObjectName("input_currency")
        self.input_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(50, 400, 380, 60))
        font = QtGui.QFont()
        font.setFamily("STHupo")
        font.setPointSize(14)
        self.input_amount.setFont(font)
        self.input_amount.setStyleSheet("background-color: #FFFACD;\n"
"border: 2px solid #6B8E23;\n"
"border-radius: 30;\n"
"color: black\n"
"")
        self.input_amount.setText("")
        self.input_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.input_amount.setObjectName("input_amount")
        self.output_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.output_currency.setGeometry(QtCore.QRect(50, 480, 380, 60))
        font = QtGui.QFont()
        font.setFamily("STHupo")
        font.setPointSize(14)
        self.output_currency.setFont(font)
        self.output_currency.setStyleSheet("background-color: #FFFACD;\n"
"border: 2px solid #6B8E23;\n"
"border-radius: 30;\n"
"color: black\n"
"")
        self.output_currency.setText("")
        self.output_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.output_currency.setObjectName("output_currency")
        self.output_amount = QtWidgets.QLabel(self.centralwidget)
        self.output_amount.setGeometry(QtCore.QRect(50, 560, 380, 60))
        font = QtGui.QFont()
        font.setFamily("STHupo")
        font.setPointSize(14)
        self.output_amount.setFont(font)
        self.output_amount.setStyleSheet("background-color: #FFFACD;\n"
"border: 2px solid #6B8E23;\n"
"border-radius: 30;\n"
"color: black\n"
"")
        self.output_amount.setText("...")
        self.output_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.output_amount.setObjectName("output_amount")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 660, 380, 60))
        font = QtGui.QFont()
        font.setFamily("STHupo")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #556B2F ;\n"
"    border-radius: 30;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    background-color: #006400 ;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CURRENCY CONVERTER"))
        self.pushButton.setText(_translate("MainWindow", "CONVERT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())